### ISSUE TITLE
[openapi][go] Integer zero value is treated as absense of field

### ISSUE THREAD

**Issue by chebykinn** [mify-io/mify#97]
If you define an object with an integer field:
```yaml
Request:
  type: object
  required:
   - value
  properties:
    value:
      type: integer
```

And then if you send a request with the value of 0, the service will return an error: "required field 'value' is zero value."
It should only trigger on null value.
